export const GET_VALUES_STARTED = 'GET_VALUES_STARTED';
export const GET_VALUES_SUCCEDED = 'GET_VALUES_SUCCEDED';
export const GET_VALUES_FAILED = 'GET_VALUES_FAILED';

export const GET_USER_PROJECTS = 'GET_USER_PROJECTS';
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS';
export const GET_USER_PROJECTS_FAILURE = 'GET_USER_PROJECTS_FAILURE';
export const ADD_USER_PROJECTS_STARTED = 'ADD_USER_PROJECTS_STARTED';
export const ADD_USER_PROJECTS_SUCCESS = 'ADD_USER_PROJECTS_SUCCESS';
export const ADD_USER_PROJECTS_FAILURE = 'ADD_USER_PROJECTS_FAILURE';
export const GET_USER_VALUES = 'GET_USER_VALUES';
export const GET_USER_VALUES_SUCCESS = 'GET_USER_VALUES_SUCCESS'
export const GET_USER_VALUES_FAILURE = 'GET_USER_VALUES_FAILURE'

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCEDED = "LOGIN_SUCCEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_STARTED ='REGISTER_STARTED';
export const REGISTER_SUCCEDED = 'REGISTER_SUCCEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGOUT = 'LOGOUT';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE';
export const VERIFICATION_START = 'VERIFICATION_START';

export const GET_USER_PROFILE_STARTED = 'GET_USER_PROFILE_STARTED';

export const GET_USER_PROFILE_SUCCEEDED = 'GET_USER_PROFILE_SUCCEEDED';

export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';
export const UPDATE_USER_PROFILE_STARTED = 'UPDATE_USER_PROFILE_STARTED';
export const UPDATE_USER_PROFILE_SUCCEEDED = 'UPDATE_USER_PROFILE_SUCCEEDED';
export const UPDATE_USER_PROFILE_FAILED = 'UPDATE_USER_PROFILE_FAILED';

export const DELETE_PROJECT_STARTED = 'DELETE_PROJECT_STARTED';
export const DELETE_PROJECT_SUCCEEDED = 'DELETE_PROJECT_SUCCEEDED';
export const DELETE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';
export const UPDATE_PROJECT_STARTED = 'UPDATE_PROJECT_STARTED';
export const UPDATE_PROJECT_SUCCEEDED = 'UPDATE_PROJECT_SUCCEEDED';
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';

export const GET_SINGLE_PROJECT_STARTED = 'GET_SINGLE_PROJECT_STARTED';
export const GET_SINGLE_PROJECT_SUCCEEDED = 'GET_SINGLE_PROJECT_SUCCEEDED';
export const GET_SINGLE_PROJECT_FAILED = 'GET_SINGLE_PROJECT_FAILED';

export const ADD_TASK_STARTED = 'ADD_TASK_FAILURE';
export const ADD_TASK_SUCCEEDED = 'ADD_TASK_SUCCEEDED';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const DELETE_TASK_STARTED = 'DELETE_TASK_STARTED';
export const DELETE_TASK_SUCCEEDED = 'DELETE_TASK_SUCCEEDED';
export const DELETE_TASK_FAILED = 'UPDATE_TASK_FAILED';
export const UPDATE_TASK_STARTED = 'UPDATE_TASK_STARTED';
export const UPDATE_TASK_SUCCEEDED = 'UPDATE_TASK_SUCCEEDED';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';

export const GET_TASKS_STARTED = 'GET_TASKS_STARTED';
export const GET_TASKS_SUCCEEDED = 'GET_TASKS_SUCCEEDED';
export const GET_TASKS_FAILED = 'GET_TASKS_FAILED';