export const GET_VALUES_STARTED = 'GET_VALUES_STARTED';
export const GET_VALUES_SUCCEDED = 'GET_VALUES_SUCCEDED';
export const GET_VALUES_FAILED = 'GET_VALUES_FAILED';

export const GET_USER_PROJECTS = 'GET_USER_PROJECTS';
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS';
export const GET_USER_PROJECTS_FAILURE = 'GET_USER_PROJECTS_FAILURE';

export const GET_USER_VALUES = 'GET_USER_VALUES';
export const GET_USER_VALUES_SUCCESS = 'GET_USER_VALUES_SUCCESS'
export const GET_USER_VALUES_FAILURE = 'GET_USER_VALUES_FAILURE'

export const GET_USER_VALUES_AND_PROJECTS = 'GET_USER_VALUES_AND_PROJECTS';
export const GET_USER_VALUES_AND_PROJECTS_SUCCESS = 'GET_USER_VALUES_AND_PROJECTS_SUCCESS';
export const GET_USER_VALUES_AND_PROJECTS_FAILURE = 'GET_USER_VALUES_AND_PROJECTS_FAILURE';

export const GET_TOP_THREE_VALUES = 'GET_TOP_THREE_VALUES';
export const GET_TOP_THREE_VALUES_SUCCESS = 'GET_TOP_THREE_VALUES_SUCCESS'; 
export const GET_TOP_THREE_VALUES_FAILURE = 'GET_TOP_THREE_VALUES_FAILURE'; 

export const ADD_NEW_USER_VALUE = ' ADD_NEW_USER_VALUE'; 

export const ADD_NEW_USER_PROJECT = 'ADD_NEW_USER_PROJECT';

// Login & Register Types
export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCEDED = "LOGIN_SUCCEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_STARTED ='REGISTER_STARTED';
export const REGISTER_SUCCEDED = 'REGISTER_SUCCEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGOUT = 'LOGOUT';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE';
export const VERIFICATION_START = 'VERIFICATION_START';

export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';

export const USER_PROFILE_SUCCEEDED = 'USER_PROFILE_SUCCEEDED';

export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';
