export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCEDED = "LOGIN_SUCCEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_STARTED ='REGISTER_STARTED';
export const REGISTER_SUCCEDED = 'REGISTER_SUCCEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGOUT = 'LOGOUT';

export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE';
export const VERIFICATION_START = 'VERIFICATION_START';
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";