export const DELETE_PROJECT_STARTED = "DELETE_PROJECT_STARTED";
export const DELETE_PROJECT_SUCCEEDED = "DELETE_PROJECT_SUCCEEDED";
export const DELETE_PROJECT_FAILED = "UPDATE_PROJECT_FAILED";

export const UPDATE_PROJECT_STARTED = "UPDATE_PROJECT_STARTED";
export const UPDATE_PROJECT_SUCCEEDED = "UPDATE_PROJECT_SUCCEEDED";
export const UPDATE_PROJECT_FAILED = "UPDATE_PROJECT_FAILED";

export const GET_SINGLE_PROJECT_STARTED = "GET_SINGLE_PROJECT_STARTED";
export const GET_SINGLE_PROJECT_SUCCEEDED = "GET_SINGLE_PROJECT_SUCCEEDED";
export const GET_SINGLE_PROJECT_FAILED = "GET_SINGLE_PROJECT_FAILED";

export const GET_USER_PROJECTS = "GET_USER_PROJECTS";
export const GET_USER_PROJECTS_SUCCESS = "GET_USER_PROJECTS_SUCCESS";
export const GET_USER_PROJECTS_FAILURE = "GET_USER_PROJECTS_FAILURE";

export const ADD_USER_PROJECTS_STARTED = "ADD_USER_PROJECTS_STARTED";
export const ADD_USER_PROJECTS_SUCCESS = "ADD_USER_PROJECTS_SUCCESS";
export const ADD_USER_PROJECTS_FAILURE = "ADD_USER_PROJECTS_FAILURE";
