export const ADD_TASK_STARTED = "ADD_TASK_FAILURE";
export const ADD_TASK_SUCCEEDED = "ADD_TASK_SUCCEEDED";
export const ADD_TASK_FAILED = "ADD_TASK_FAILED";

export const DELETE_TASK_STARTED = "DELETE_TASK_STARTED";
export const DELETE_TASK_SUCCEEDED = "DELETE_TASK_SUCCEEDED";
export const DELETE_TASK_FAILED = "UPDATE_TASK_FAILED";

export const UPDATE_TASK_STARTED = "UPDATE_TASK_STARTED";
export const UPDATE_TASK_SUCCEEDED = "UPDATE_TASK_SUCCEEDED";
export const UPDATE_TASK_FAILED = "UPDATE_TASK_FAILED";

export const GET_TASKS_STARTED = "GET_TASKS_STARTED";
export const GET_TASKS_SUCCEEDED = "GET_TASKS_SUCCEEDED";
export const GET_TASKS_FAILED = "GET_TASKS_FAILED";
