export const GET_USER_PROFILE_STARTED = "GET_USER_PROFILE_STARTED";
export const GET_USER_PROFILE_SUCCEEDED = "GET_USER_PROFILE_SUCCEEDED";
export const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED";

export const UPDATE_USER_PROFILE_STARTED = "UPDATE_USER_PROFILE_STARTED";
export const UPDATE_USER_PROFILE_SUCCEEDED = "UPDATE_USER_PROFILE_SUCCEEDED";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";

export const GET_TOP_VALUES_STARTED = "GET_TOP_VALUES_STARTED";
export const GET_TOP_VALUES_SUCCEEDED = "GET_TOP_VALUES_SUCCEEDED";
export const GET_TOP_VALUES_FAILED = "GET_TOP_VALUES_FAILED";

export const ADD_TOP_VALUES_STARTED = "ADD_TOP_VALUES_STARTED";
export const ADD_TOP_VALUES_SUCCEEDED = "ADD_TOP_VALUES_SUCCEEDED";
export const ADD_TOP_VALUES_FAILED = "ADD_TOP_VALUES_FAILED";

export const GET_USER_VALUES = "GET_USER_VALUES";
export const GET_USER_VALUES_SUCCESS = "GET_USER_VALUES_SUCCESS";
export const GET_USER_VALUES_FAILURE = "GET_USER_VALUES_FAILURE";

export const DELETE_TOP_VALUES_STARTED = "DELETE_TOP_VALUES_STARTED";
export const DELETE_TOP_VALUES_SUCCEEDED = "DELETE_TOP_VALUES_SUCCEEDED";
export const DELETE_TOP_VALUES_FAILED = "DELETE_TOP_VALUES_FAILED";