export const GET_VALUES_STARTED = "GET_VALUES_STARTED";
export const GET_VALUES_SUCCEDED = "GET_VALUES_SUCCEDED";
export const GET_VALUES_FAILED = "GET_VALUES_FAILED";
export const SELECTED_PROJECT_VALUE = "SELECTED_PROJECT_VALUE";
